/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhereAreTheSunAndMoonRouteImport } from './routes/where-are-the-sun-and-moon'
import { Route as SolarSystemRouteImport } from './routes/solar-system'
import { Route as IndexRouteImport } from './routes/index'

const WhereAreTheSunAndMoonRoute = WhereAreTheSunAndMoonRouteImport.update({
  id: '/where-are-the-sun-and-moon',
  path: '/where-are-the-sun-and-moon',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSystemRoute = SolarSystemRouteImport.update({
  id: '/solar-system',
  path: '/solar-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solar-system': typeof SolarSystemRoute
  '/where-are-the-sun-and-moon': typeof WhereAreTheSunAndMoonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solar-system': typeof SolarSystemRoute
  '/where-are-the-sun-and-moon': typeof WhereAreTheSunAndMoonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solar-system': typeof SolarSystemRoute
  '/where-are-the-sun-and-moon': typeof WhereAreTheSunAndMoonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solar-system' | '/where-are-the-sun-and-moon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solar-system' | '/where-are-the-sun-and-moon'
  id: '__root__' | '/' | '/solar-system' | '/where-are-the-sun-and-moon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolarSystemRoute: typeof SolarSystemRoute
  WhereAreTheSunAndMoonRoute: typeof WhereAreTheSunAndMoonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/where-are-the-sun-and-moon': {
      id: '/where-are-the-sun-and-moon'
      path: '/where-are-the-sun-and-moon'
      fullPath: '/where-are-the-sun-and-moon'
      preLoaderRoute: typeof WhereAreTheSunAndMoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-system': {
      id: '/solar-system'
      path: '/solar-system'
      fullPath: '/solar-system'
      preLoaderRoute: typeof SolarSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolarSystemRoute: SolarSystemRoute,
  WhereAreTheSunAndMoonRoute: WhereAreTheSunAndMoonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
